### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wohahobg** [BlackyPaw/I18N#6]
I just install the plugin and got this problem

`> [20:48:34 INFO]: Wohaho issued server command: /lang
> [20:48:34 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lang' in plugin I18N v1.3.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-2cf50f0-2b93d83]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at com.blackypaw.mc.i18n.command.CommandLanguage.onCommand(CommandLanguage.java:57) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-2cf50f0-2b93d83]
... 15 more`

http://prntscr.com/lcu44d ProtocolLib
I18N http://prntscr.com/lcu4ds

**Comment by cieldeville** [comment]
Which Spigot version are you using? I have not updated this project to newer releases of the server software in a while and since it is heavily intercepting and modifying networks packets it is likely that it broke in a more recent version due to changes in the underlying network protocol.

**Comment by wohahobg** [comment]
I am using last version of 1.12.2 . I hope u will update I just was looking for plugin like that which can translete plugins messages even. thanks.

**Comment by cieldeville** [comment]
It shouldn't take a lot of work to update the plugin the the latest release of Spigot. I will try to update the codebase this weekend.

**Comment by wohahobg** [comment]
Aww okey I will wait it! Thanks!

**Comment by cieldeville** [comment]
I have tested the plugin thouroughly these last few days but I am unable to reproduce the error you posted above using Spigot version 1.12.2 - could you give me further details on how to reproduce this error?
